### ISSUE TITLE
Display units in mmol

### ISSUE THREAD

**Issue by Schoggiweggli** [mddub/nightscout-osx-menubar#2]
Would be great if we could configure the app to use mmol as unit instead of mgdl.

**Comment by mddub** [comment]
Thanks for the feature request! I just added support for mmol/L in version 0.3.0. Please let me know if it works for you.

![](https://raw.githubusercontent.com/mddub/nightscout-osx-menubar/86a9215271bcb50cd41fad5eabfeb7153313d85e/screenshot.png)

**Comment by Schoggiweggli** [comment]
Works great, thanks!
